import type { Metadata } from "next";
import Link from "next/link";
import { site } from "@/content/site";

export const metadata: Metadata = {
  title: "Setpoint AI — Terms of Service",
  description:
    "Terms of service for Setpoint AI, an AI-powered workout planning and tracking app.",
  alternates: {
    canonical: "/setpoint/terms",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function SetpointTermsPage() {
  return (
    <main id="main" className="flex-1">
      <section className="border-b border-border">
        <div className="mx-auto w-full max-w-3xl px-5 py-16 sm:px-8 sm:py-20">
          <Link
            href="/setpoint"
            className="font-mono text-[11px] font-medium uppercase tracking-[0.22em] text-accent hover:text-accent-hover transition-colors"
          >
            ← Setpoint AI
          </Link>
          <h1 className="mt-3 font-display text-3xl tracking-tight text-foreground sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-2 text-sm text-muted">
            Effective date: September 16, 2026
          </p>
        </div>
      </section>

      <section>
        <div className="mx-auto w-full max-w-3xl px-5 py-12 sm:px-8 sm:py-16">
          <div className="space-y-10 text-base leading-7 text-muted">
            <div>
              <h2 className="text-lg font-semibold text-foreground">
                1. Acceptance of Terms
              </h2>
              <p className="mt-3">
                By downloading, installing, or using Setpoint AI
                (&quot;the App&quot;), you agree to be bound by these Terms of
                Service (&quot;Terms&quot;). If you do not agree, do not use
                the App. The App is developed and operated by {site.name}{" "}
                (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                2. Description of Service
              </h2>
              <p className="mt-3">
                Setpoint AI is a fitness application that uses artificial
                intelligence to generate personalized workout plans. The App
                also allows you to log exercises, track sets and reps, monitor
                progress over time, and manage your training schedule.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                3. Account Registration
              </h2>
              <p className="mt-3">
                You must create an account to use Setpoint AI. You are
                responsible for maintaining the confidentiality of your login
                credentials and for all activity that occurs under your
                account. You agree to provide accurate information during
                registration and to notify us promptly of any unauthorized use
                of your account.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                4. Health & Fitness Disclaimer
              </h2>
              <p className="mt-3">
                Setpoint AI provides AI-generated workout suggestions for
                informational purposes only.{" "}
                <strong className="text-foreground">
                  The App is not a substitute for professional medical advice,
                  diagnosis, or treatment.
                </strong>{" "}
                Always consult a qualified healthcare provider before starting
                any exercise program. You use the App and follow its
                recommendations entirely at your own risk.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                5. AI-Generated Content
              </h2>
              <p className="mt-3">
                Workout plans generated by the AI are suggestions based on the
                preferences and data you provide. We do not guarantee the
                accuracy, completeness, or suitability of any AI-generated
                recommendation. You should evaluate each suggestion and adjust
                it to fit your fitness level and any medical conditions.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                6. User Data & Privacy
              </h2>
              <p className="mt-3">
                Your use of the App is also governed by our{" "}
                <Link
                  href="/setpoint/privacy"
                  className="text-accent hover:text-accent-hover transition-colors"
                >
                  Privacy Policy
                </Link>
                , which describes the data we collect and how it is used. By
                using the App, you consent to our data practices as described
                in the Privacy Policy.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                7. Acceptable Use
              </h2>
              <p className="mt-3">You agree not to:</p>
              <ul className="mt-3 list-disc space-y-2 pl-5">
                <li>
                  Use the App for any unlawful purpose or in violation of any
                  applicable laws
                </li>
                <li>
                  Attempt to gain unauthorized access to the App&apos;s systems
                  or other users&apos; accounts
                </li>
                <li>
                  Reverse-engineer, decompile, or disassemble any part of the
                  App
                </li>
                <li>
                  Interfere with or disrupt the App&apos;s infrastructure or
                  services
                </li>
                <li>
                  Use automated scripts or bots to interact with the App
                </li>
              </ul>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                8. Intellectual Property
              </h2>
              <p className="mt-3">
                All content, design, code, and branding associated with
                Setpoint AI are owned by {site.name} and are protected by
                applicable intellectual property laws. You retain ownership of
                any personal data and workout logs you create within the App.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                9. Termination
              </h2>
              <p className="mt-3">
                We reserve the right to suspend or terminate your account at
                any time if you violate these Terms. You may delete your
                account at any time by contacting us at{" "}
                <a
                  href={`mailto:${site.email}?subject=Setpoint%20AI%20Account%20Deletion`}
                  className="text-accent hover:text-accent-hover transition-colors"
                >
                  {site.email}
                </a>
                . Upon termination, your data will be permanently deleted in
                accordance with our Privacy Policy.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                10. Limitation of Liability
              </h2>
              <p className="mt-3">
                To the fullest extent permitted by law, {site.name} shall not
                be liable for any indirect, incidental, special, consequential,
                or punitive damages arising out of or related to your use of
                the App. The App is provided on an &quot;as is&quot; and
                &quot;as available&quot; basis without warranties of any kind,
                either express or implied.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                11. Changes to These Terms
              </h2>
              <p className="mt-3">
                We may update these Terms from time to time. The revised
                version will be posted on this page with an updated effective
                date. Continued use of the App after changes constitutes
                acceptance of the revised Terms.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                12. Governing Law
              </h2>
              <p className="mt-3">
                These Terms are governed by and construed in accordance with
                the laws of the State of Texas, without regard to conflict of
                law principles.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-foreground">
                Contact
              </h2>
              <p className="mt-3">
                Questions about these terms? Reach out at{" "}
                <a
                  href={`mailto:${site.email}`}
                  className="text-accent hover:text-accent-hover transition-colors"
                >
                  {site.email}
                </a>
                .
              </p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
